### ISSUE TITLE
Add styles to flash notices

### ISSUE THREAD

**Issue by JoaoGabrielMoura** [IcaliaLabs/watcher#104]
They're on views/admin/repositories/index and views/devise/sessions/new

**Comment by mayra-cabrera** [comment]
can you add an screenshot? Just to make it more clear

**Comment by JoaoGabrielMoura** [comment]
![image](https://cloud.githubusercontent.com/assets/7563339/17864352/5a8c2a0e-6863-11e6-8e94-538d8abec456.png)

![image](https://cloud.githubusercontent.com/assets/7563339/17864359/603d9604-6863-11e6-92c0-b2b2be3a1685.png)
