### ISSUE TITLE
Build dashboard for general information

### ISSUE THREAD

**Issue by mayra-cabrera** [IcaliaLabs/watcher#3]
- [ ] # Repositories
- [ ] # Public repositories
- [ ] # Private Repositories
- [ ] # Open issues
- [ ] # Open pull requests
- [ ] # Stars
- [ ] # Commits ?

**Comment by mayra-cabrera** [comment]
This could be a nice approach: http://dashingdemo.herokuapp.com/sample what do you think? @thelastinuit

**Comment by thelastinuit** [comment]
Possible sections for landing page:
- Open Issues (count)
- Open Repos (count)
- Stars (I don't know why but I can't stop thinking in Mario Bros)
- Open Pull Requests
- Commits

anything else? Suggestions?

**Comment by kurenn** [comment]
CodeClimate average grade, open pull requests, deploys?

**Comment by thelastinuit** [comment]
@kurenn good!
