### ISSUE TITLE
Listing commits for a branch not working properly

### ISSUE THREAD

**Issue by mayra-cabrera** [IcaliaLabs/watcher#41]
Steps to repro:

1. Request commits for a specific branch, i.e:

```
http://localhost:3000/api/v1/commits/icalialabs/watcher/organization_model
```

2. The following is return

```
{"sha":"ab20f0f5671a9bd482bea9292178916ad7e4db3b","author":"PedroASGarza","message":"Merge branch 'organization_model' of https://github.com/IcaliaLabs/watcher into organization_model","stats":{"additions":1,"deletions":6,"total":7}}
```

Which is the last commit of `organization_model`, but what we want is all commits that are in `organization_model` and that haven't been merged with master. Also ensure that dates options are working properly

**Comment by PedroASGarza** [comment]
correct routing:
`/api/v1/commits/IcaliaLabs/watcher?branch=organization_model`
also receives:
`api/v1/commits/IcaliaLabs/watcher?since=%202016-01-30&until=2016-06-30&branch=organization_model`
