### ISSUE TITLE
Add total lines column in commits index

### ISSUE THREAD

**Issue by mayra-cabrera** [IcaliaLabs/watcher#85]
![screen shot 2016-08-14 at 12 53 08 pm](https://cloud.githubusercontent.com/assets/4439027/17650861/1918b4a2-621e-11e6-964b-f39c2c679869.png)

**Comment by mayra-cabrera** [comment]
@JoaoGabrielMoura there's no total column at commits index 

![screen shot 2016-08-18 at 5 08 06 pm](https://cloud.githubusercontent.com/assets/4439027/17792457/6a658466-6566-11e6-8409-ba71710a1272.png)

also can you checked with @saraleon what's going with calendar fields?

**Comment by JoaoGabrielMoura** [comment]
I just added the total to the pr, I removed it by accident when fixing conflicts... I need help form @saraleon to fix the styles because the columns don't fit when adding one more column. And I'm not sure what happened with the calendar fields, it is like this on master.

**Comment by mayra-cabrera** [comment]
@JoaoGabrielMoura the PR has been merged, you need to make another branch / PR. Please check with @saraleon what to do with columns & calendar fields

**Comment by mayra-cabrera** [comment]
@JoaoGabrielMoura I've already talked to @saraleon, she's gonna fix those text field on mondays. Can you just add the total column ? Also it will be awesome if the submit respond with an `js.erb` instead of re-rendering the complete page
